server:
  port: 9191

spring:
  application:
    name: pokemon-gateway-service
  cloud:
    gateway:
      routes:
        - id: pokemon-api
          uri: lb://POKEMON-API
          predicates:
            - Path=/api/**
          filters:
            - TokenAuthenticationFilter
        - id: nomad-auth-service
          uri: lb://NOMAD-AUTH-SERVICE
          predicates:
            - Path=/signin
            - Path=/signup

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret-key: 2D4A614E645267556B58703233357638792F413F4428472B4B6250655368566D
